### ISSUE TITLE
Multiple changes what section text, color

### ISSUE THREAD

**Issue by rrtigga** [HackingEDU/main-hackathon-website#16]
WHAT 
- let's try this section in white, next one grey
- decrease font weight on "What is HackingEDU" & other headings, try to match the mockup
- justify paragraph text (mobile also)
- remove mandela from quote (i know i asked to add it, but doesn't look good in this format)
- on mobile: theres a white stripe in btwn this & learn section.

Mockup Here: 

![rishabhmockup](https://cloud.githubusercontent.com/assets/6754090/8534937/209482fe-23f6-11e5-8dda-f5980a05ef42.jpg)

**Comment by ksatan** [comment]
The rest is done.
Change backgrounds to: white, grey, white
