### ISSUE TITLE
<a> tags around li items

### ISSUE THREAD

**Issue by rrtigga** [HackingEDU/main-hackathon-website#27]
You need to add display:block to your <a> tags, then you can set a width and height or padding

Currently for the apply button on nav bar, the whole button isn't clickable (try clickable the sides)

**Comment by dooks** [comment]
You shouldn't surround `<li>` tags with anything to keep the `<ul>` hierarchy flat. Instead, the `<a>` tag within should have `display: block; width: 100%; height: 100%`.
