### ISSUE TITLE
when the nav bar is clicked, item stays highlighted.

### ISSUE THREAD

**Issue by rrtigga** [HackingEDU/main-hackathon-website#28]
When a nav bar item is clicked, the text stays highlighted for a time while scrolling down to the section and it is a bit jumpy. Might be a javascript issue, or conflicting css class? Either way let's fix ;)

**Comment by leethomas** [comment]
This was fixed 4 days ago with https://github.com/HackingEDU/main-hackathon-website/commit/1268982adca7cfcb38b7636ba368f0e114550b76.
