### ISSUE TITLE
Press Section

### ISSUE THREAD

**Issue by rrtigga** [HackingEDU/main-hackathon-website#50]
Work still needs to be done:

Point "click here" link to somewhere
Adjust margin for bottom strong element
Normalize widths when scaling to mobile
Change BerkeleyByte logo to something not just totally print-screened from the website

**Comment by leethomas** [comment]
I think it's best to ask BrekelyByte to send us a copy of their logo.

**Comment by ksatan** [comment]
their logo is strait up css lol

**Comment by ksatan** [comment]
i guess we can just do the same

**Comment by ksatan** [comment]
![image](https://cloud.githubusercontent.com/assets/5365497/8900321/c695ca0c-33f3-11e5-80bb-babe5cc29687.png)
